### ISSUE TITLE
Add text for when player has only a single life remaining

### ISSUE THREAD

**Issue by kdv24** [ahl389/paint-run2#25]
Right now if a player loses two lives, the text displays as follows:

<img width="1008" alt="Screen Shot 2019-05-23 at 1 26 43 PM" src="https://user-images.githubusercontent.com/6107653/58284395-5ac90780-7d5f-11e9-9506-c0dac8b50a8a.png">

 
1. Start the game
2. Lose twice 
3. Notice the first time you lose, the text at top of screen correctly shows "You have two lives remaining" but when you're down to one life, it displays "You have 1 live**s** remaining."

**Expected behavior**
Text should display "You have 1 life remaining."

**Comment by brragul** [comment]
Hi @kdv24 
I can work on this issue if it is not fixed yet.

**Comment by kdv24** [comment]
Hi @brragul 👋 
I really think I already fixed it and a couple other things at the end of May, but I can't find a record of any of them anywhere in the repo.  🤷‍♀ So, go for it.  Thanks!

**Comment by brragul** [comment]
You are right I can see the fix [here](https://github.com/ahl389/paint-run2/blob/8210c6421f968d73e59ade5c2e6080e2e9bc41e2/src/components/Level/Level.js#L99).
But I can still see the issue in https://ahl389.github.io/paint-run2/. I will look into other issue in the project thanks.
